In [4]:
import gym
import gym.spaces
import numpy as np

In [6]:
env = gym.make('FrozenLake-v0')

In [8]:
#Initialize table with all zeros
Q = np.zeros([env.observation_space.n,env.action_space.n])
# Set learning parameters
lr = .8
y = .95
num_episodes = 2000
#create lists to contain total rewards and steps per episode
#jList = []
rList = []
for i in range(num_episodes):
    #Reset environment and get first new observation
    s = env.reset()
    rAll = 0
    d = False
    j = 0
    #The Q-Table learning algorithm
    while j < 99:
        j+=1
        #Choose an action by greedily (with noise) picking from Q table
        a = np.argmax(Q[s,:] + np.random.randn(1,env.action_space.n)*(1./(i+1)))
        #Get new state and reward from environment
        s1,r,d,_ = env.step(a)
        #Update Q-Table with new knowledge
        Q[s,a] = Q[s,a] + lr*(r + y*np.max(Q[s1,:]) - Q[s,a])
        rAll += r
        s = s1
        if d == True:
            break
    #jList.append(j)
    rList.append(rAll)

In [9]:
print "Score over time: " +  str(sum(rList)/num_episodes)

Score over time: 0.4945


In [11]:
print  "Final Q-Table Values"
print Q

Final Q-Table Values
[[1.18791066e-01 4.92624031e-03 1.19954550e-02 1.00975571e-02]
 [3.42856499e-04 3.76405230e-04 5.59931812e-04 2.44701889e-01]
 [2.20238265e-03 2.37239028e-03 1.28519045e-03 3.82615912e-02]
 [4.13212242e-04 4.26126405e-04 7.78474593e-04 5.49453847e-03]
 [1.17668989e-01 1.44705390e-03 7.72129294e-04 9.81869164e-04]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [5.63088735e-05 1.71136736e-05 5.70225294e-03 1.15430909e-04]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.09607840e-03 2.79280838e-03 1.95623085e-03 1.39672030e-01]
 [2.83516858e-04 2.27160425e-01 1.51801010e-03 1.31920098e-04]
 [7.65987387e-01 3.57298540e-04 1.71626117e-04 1.30983529e-04]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [3.21593796e-03 7.82017987e-04 4.08527578e-01 8.00978708e-04]
 [0.00000000e+00 0.00000000e+00 9.97880912e-01 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.